version: '3'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    depends_on:
      - elasticsearch
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://:5000"
        syslog-facility: daemon

  discovery:
    image: aibrahem/eureka_service
    ports:
      - "8761:8761"
    depends_on:
      - zipkin
      - elasticsearch
    links:
      - zipkin
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://:5000"
        syslog-facility: daemon
        
  aggregator:
    image: aibrahem/aggregator
    ports:
      - "8083:8083"
    depends_on:
      - zipkin
      - discovery
      - elasticsearch
    links:
      - zipkin
      - discovery
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://:5000"
        syslog-facility: daemon
  
  vehicle_service:
    image: aibrahem/vehicle_service
    ports:
      - "8082:8082"
    depends_on:
      - zipkin
      - discovery
      - elasticsearch
    links:
      - zipkin
      - discovery
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://:5000"
        syslog-facility: daemon

  user_details:
    image: aibrahem/user_details
    ports:
      - "8081:8081"
    depends_on:
      - zipkin
      - discovery
      - elasticsearch
    links:
      - zipkin
      - discovery
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://:5000"
        syslog-facility: daemon

networks:

  elk:
    driver: bridge
